import Head from 'next/head'

const Home = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={'/favicon.ico'} />
      </Head>

      <main>
        <h1>NextJS</h1>
      </main>
    </div>
  )
}

export default Home
